### ISSUE TITLE
Porting of extant geospatial software developed by CASAS to GRASS GIS 8

### ISSUE THREAD

**Issue by neteler** [casasglobal-org/casas-gis#112]
## Tasks

The purpose of this issue is to assist in the tracking of progress. This "living document" task list may be edited as needed.

### Data format upgrade of GRASS 6.4 CASAS database

- [ ] Conversion of  GRASS 6.4 CASAS database to GRASS GIS 8:
  - grassdata format conversion scripts added (#107)
  - scripts: upgrade from GRASS GIS 6 to GRASS GIS 8 (#108)

### Software improvements from GRASS GIS 6 to 8

- [ ] `casas_gis_old`: initial file organization restructuring (#107)
- [ ] Software improvements (in `casas_gis_old`): minor cleanups such as removing leftover files and reorganizing directory structures (#109)
- [ ] GRASS GIS related scripts: fix formatting issues in the parser section to ensure consistency across the codebase (#110)
- [ ] GRASS GIS 8 related updates and wider usage of variable for paths (#111)
- [ ] Extend CASAS GIS functionality to map any region (e.g., countries, continents, or custom bounding boxes) or the entire globe.
- [ ] Revisit workflows in the script for potential optimization
- [ ] Draft Python Jupyter Notebooks for further geospatial analysis and graphics.

### Documentation

- [ ] Document the use of developed software

### Cloud optimization

- [ ] Explore an https://actinia.mundialis.de/ implementation for local and cloud deployment.
